/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicOffersRouteImport } from './routes/_public.offers'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicBookingRouteImport } from './routes/_public.booking'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOffersRoute = PublicOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookingRoute = PublicBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/offers': typeof PublicOffersRoute
  '/services': typeof PublicServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/offers': typeof PublicOffersRoute
  '/services': typeof PublicServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/booking': typeof PublicBookingRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/offers': typeof PublicOffersRoute
  '/_public/services': typeof PublicServicesRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/offers'
    | '/services'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/offers'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/offers'
    | '/services'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/offers'
    | '/admin/services'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/api/public/track'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/about'
    | '/_public/booking'
    | '/_public/contact'
    | '/_public/gallery'
    | '/_public/offers'
    | '/_public/services'
    | '/admin/appointments'
    | '/admin/dashboard'
    | '/admin/gallery'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/offers'
    | '/admin/services'
    | '/admin/settings'
    | '/_public/'
    | '/admin/'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/offers': {
      id: '/_public/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof PublicOffersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booking': {
      id: '/_public/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof PublicBookingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBookingRoute: typeof PublicBookingRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicOffersRoute: typeof PublicOffersRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBookingRoute: PublicBookingRoute,
  PublicContactRoute: PublicContactRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicOffersRoute: PublicOffersRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
