/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoiRouteImport } from './routes/soi'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as SoiIndexRouteImport } from './routes/soi.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as SoiSettingsRouteImport } from './routes/soi.settings'
import { Route as SoiServicesRouteImport } from './routes/soi.services'
import { Route as SoiOffersRouteImport } from './routes/soi.offers'
import { Route as SoiLoginRouteImport } from './routes/soi.login'
import { Route as SoiInquiriesRouteImport } from './routes/soi.inquiries'
import { Route as SoiGalleryRouteImport } from './routes/soi.gallery'
import { Route as SoiDashboardRouteImport } from './routes/soi.dashboard'
import { Route as SoiAppointmentsRouteImport } from './routes/soi.appointments'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicOffersRouteImport } from './routes/_public.offers'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicBookingRouteImport } from './routes/_public.booking'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'

const SoiRoute = SoiRouteImport.update({
  id: '/soi',
  path: '/soi',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const SoiIndexRoute = SoiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SoiRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const SoiSettingsRoute = SoiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SoiRoute,
} as any)
const SoiServicesRoute = SoiServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SoiRoute,
} as any)
const SoiOffersRoute = SoiOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => SoiRoute,
} as any)
const SoiLoginRoute = SoiLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SoiRoute,
} as any)
const SoiInquiriesRoute = SoiInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => SoiRoute,
} as any)
const SoiGalleryRoute = SoiGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SoiRoute,
} as any)
const SoiDashboardRoute = SoiDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SoiRoute,
} as any)
const SoiAppointmentsRoute = SoiAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => SoiRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOffersRoute = PublicOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookingRoute = PublicBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/soi': typeof SoiRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/offers': typeof PublicOffersRoute
  '/services': typeof PublicServicesRoute
  '/soi/appointments': typeof SoiAppointmentsRoute
  '/soi/dashboard': typeof SoiDashboardRoute
  '/soi/gallery': typeof SoiGalleryRoute
  '/soi/inquiries': typeof SoiInquiriesRoute
  '/soi/login': typeof SoiLoginRoute
  '/soi/offers': typeof SoiOffersRoute
  '/soi/services': typeof SoiServicesRoute
  '/soi/settings': typeof SoiSettingsRoute
  '/soi/': typeof SoiIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/offers': typeof PublicOffersRoute
  '/services': typeof PublicServicesRoute
  '/soi/appointments': typeof SoiAppointmentsRoute
  '/soi/dashboard': typeof SoiDashboardRoute
  '/soi/gallery': typeof SoiGalleryRoute
  '/soi/inquiries': typeof SoiInquiriesRoute
  '/soi/login': typeof SoiLoginRoute
  '/soi/offers': typeof SoiOffersRoute
  '/soi/services': typeof SoiServicesRoute
  '/soi/settings': typeof SoiSettingsRoute
  '/': typeof PublicIndexRoute
  '/soi': typeof SoiIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/soi': typeof SoiRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/booking': typeof PublicBookingRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/offers': typeof PublicOffersRoute
  '/_public/services': typeof PublicServicesRoute
  '/soi/appointments': typeof SoiAppointmentsRoute
  '/soi/dashboard': typeof SoiDashboardRoute
  '/soi/gallery': typeof SoiGalleryRoute
  '/soi/inquiries': typeof SoiInquiriesRoute
  '/soi/login': typeof SoiLoginRoute
  '/soi/offers': typeof SoiOffersRoute
  '/soi/services': typeof SoiServicesRoute
  '/soi/settings': typeof SoiSettingsRoute
  '/_public/': typeof PublicIndexRoute
  '/soi/': typeof SoiIndexRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/soi'
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/offers'
    | '/services'
    | '/soi/appointments'
    | '/soi/dashboard'
    | '/soi/gallery'
    | '/soi/inquiries'
    | '/soi/login'
    | '/soi/offers'
    | '/soi/services'
    | '/soi/settings'
    | '/soi/'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/booking'
    | '/contact'
    | '/gallery'
    | '/offers'
    | '/services'
    | '/soi/appointments'
    | '/soi/dashboard'
    | '/soi/gallery'
    | '/soi/inquiries'
    | '/soi/login'
    | '/soi/offers'
    | '/soi/services'
    | '/soi/settings'
    | '/'
    | '/soi'
    | '/api/public/track'
  id:
    | '__root__'
    | '/_public'
    | '/soi'
    | '/_public/about'
    | '/_public/booking'
    | '/_public/contact'
    | '/_public/gallery'
    | '/_public/offers'
    | '/_public/services'
    | '/soi/appointments'
    | '/soi/dashboard'
    | '/soi/gallery'
    | '/soi/inquiries'
    | '/soi/login'
    | '/soi/offers'
    | '/soi/services'
    | '/soi/settings'
    | '/_public/'
    | '/soi/'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  SoiRoute: typeof SoiRouteWithChildren
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soi': {
      id: '/soi'
      path: '/soi'
      fullPath: '/soi'
      preLoaderRoute: typeof SoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soi/': {
      id: '/soi/'
      path: '/'
      fullPath: '/soi/'
      preLoaderRoute: typeof SoiIndexRouteImport
      parentRoute: typeof SoiRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/soi/settings': {
      id: '/soi/settings'
      path: '/settings'
      fullPath: '/soi/settings'
      preLoaderRoute: typeof SoiSettingsRouteImport
      parentRoute: typeof SoiRoute
    }
    '/soi/services': {
      id: '/soi/services'
      path: '/services'
      fullPath: '/soi/services'
      preLoaderRoute: typeof SoiServicesRouteImport
      parentRoute: typeof SoiRoute
    }
    '/soi/offers': {
      id: '/soi/offers'
      path: '/offers'
      fullPath: '/soi/offers'
      preLoaderRoute: typeof SoiOffersRouteImport
      parentRoute: typeof SoiRoute
    }
    '/soi/login': {
      id: '/soi/login'
      path: '/login'
      fullPath: '/soi/login'
      preLoaderRoute: typeof SoiLoginRouteImport
      parentRoute: typeof SoiRoute
    }
    '/soi/inquiries': {
      id: '/soi/inquiries'
      path: '/inquiries'
      fullPath: '/soi/inquiries'
      preLoaderRoute: typeof SoiInquiriesRouteImport
      parentRoute: typeof SoiRoute
    }
    '/soi/gallery': {
      id: '/soi/gallery'
      path: '/gallery'
      fullPath: '/soi/gallery'
      preLoaderRoute: typeof SoiGalleryRouteImport
      parentRoute: typeof SoiRoute
    }
    '/soi/dashboard': {
      id: '/soi/dashboard'
      path: '/dashboard'
      fullPath: '/soi/dashboard'
      preLoaderRoute: typeof SoiDashboardRouteImport
      parentRoute: typeof SoiRoute
    }
    '/soi/appointments': {
      id: '/soi/appointments'
      path: '/appointments'
      fullPath: '/soi/appointments'
      preLoaderRoute: typeof SoiAppointmentsRouteImport
      parentRoute: typeof SoiRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/offers': {
      id: '/_public/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof PublicOffersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booking': {
      id: '/_public/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof PublicBookingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBookingRoute: typeof PublicBookingRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicOffersRoute: typeof PublicOffersRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBookingRoute: PublicBookingRoute,
  PublicContactRoute: PublicContactRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicOffersRoute: PublicOffersRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface SoiRouteChildren {
  SoiAppointmentsRoute: typeof SoiAppointmentsRoute
  SoiDashboardRoute: typeof SoiDashboardRoute
  SoiGalleryRoute: typeof SoiGalleryRoute
  SoiInquiriesRoute: typeof SoiInquiriesRoute
  SoiLoginRoute: typeof SoiLoginRoute
  SoiOffersRoute: typeof SoiOffersRoute
  SoiServicesRoute: typeof SoiServicesRoute
  SoiSettingsRoute: typeof SoiSettingsRoute
  SoiIndexRoute: typeof SoiIndexRoute
}

const SoiRouteChildren: SoiRouteChildren = {
  SoiAppointmentsRoute: SoiAppointmentsRoute,
  SoiDashboardRoute: SoiDashboardRoute,
  SoiGalleryRoute: SoiGalleryRoute,
  SoiInquiriesRoute: SoiInquiriesRoute,
  SoiLoginRoute: SoiLoginRoute,
  SoiOffersRoute: SoiOffersRoute,
  SoiServicesRoute: SoiServicesRoute,
  SoiSettingsRoute: SoiSettingsRoute,
  SoiIndexRoute: SoiIndexRoute,
}

const SoiRouteWithChildren = SoiRoute._addFileChildren(SoiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  SoiRoute: SoiRouteWithChildren,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
